### ISSUE TITLE
Error while loading plugin 'ranger_plugin_feedranger'

### ISSUE THREAD

**Issue by qoxxxx** [stefandtw/feedranger#1]
I'm getting 
`Error while loading plugin 'ranger_plugin_feedranger'`
when starting Ranger.

Any idea ?

**Comment by stefandtw** [comment]
Are there any error messages when you `:display_log` in ranger? Also the output of `ranger --version` might be useful.

**Comment by qoxxxx** [comment]
Here's :display_log
```
Message Log:
17:57:18 INFO ranger version: ranger-master 1.9.2
17:57:18 INFO Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
17:57:18 INFO Locale: None.None
17:57:18 INFO Process ID: 8372
17:57:18 ERRO Error while loading plugin 'ranger_plugin_feedranger'
17:57:18 ERRO invalid syntax (ranger_plugin_feedranger.py, line 70)
Traceback (most recent call last):
  File "/home/user/app/ranger/ranger/core/main.py", line 435, in load_settings
    module = importlib.import_module('plugins.' + plugin)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/.config/ranger/plugins/ranger_plugin_feedranger.py", line 70
    fm.execute_console(f"setlocal path={dirrec}$ sort feeds")
                                                           ^
SyntaxError: invalid syntax
17:57:18 ERRO Notification: Error while loading plugin 'ranger_plugin_feedranger'
```

**Comment by stefandtw** [comment]
The plug-in did not work with Python 2.7. Please try again now.
You also need to install an extra package.
`sudo pip install futures`

**Comment by qoxxxx** [comment]
Ranger crashes as soon as I enter ~/.local/share/feedparser : 

```
ranger version: ranger-master 1.9.2
Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Locale: None.None
Current file: '/home/user/.local/share/feedranger/>>>>  Software  >>>>>>>>>>'

Traceback (most recent call last):
  File "/home/user/app/ranger/ranger/core/main.py", line 190, in main
    fm.loop()
  File "/home/user/app/ranger/ranger/core/fm.py", line 398, in loop
    ui.redraw()
  File "/home/user/app/ranger/ranger/gui/ui.py", line 341, in redraw
    self.draw()
  File "/home/user/app/ranger/ranger/gui/ui.py", line 368, in draw
    DisplayableContainer.draw(self)
  File "/home/user/app/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/user/app/ranger/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/home/user/app/ranger/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/home/user/app/ranger/ranger/gui/widgets/browsercolumn.py", line 186, in draw
    self._draw_directory()
  File "/home/user/app/ranger/ranger/gui/widgets/browsercolumn.py", line 372, in _draw_directory
    infostringdata = current_linemode.infostring(drawn, metadata)
  File "/home/user/.config/ranger/plugins/ranger_plugin_feedranger.py", line 130, in infostring
    return super().infostring(file, metadata)
TypeError: super() takes at least 1 argument (0 given)
```

It's working fine with python3 though.

**Comment by stefandtw** [comment]
I missed that. Should be fixed now.
